#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Sep 16, 2018 04:12:39 PM +0300  platform: Windows NT

import sys
import encryptImg
import ctypes

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
    
from tkinter import messagebox


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, root, top
    root = Tk()
    top = ImageHide (root)
    root.mainloop()

def destroy_ImageHide():
    global w
    w.destroy()
    w = None
    
def setCommand():
    global top
    path = top.etSetPath.get().strip()
    message = top.etSetMessage.get().strip()
    newName = top.etNewName.get().strip()
    if (len(path) <= 4):
        messagebox.showerror("Error", "No legal path provided.")
        return
    elif (len(message) == 0):
        messagebox.showerror("Error", "No message provided.")
        return
    elif (path[-4:] != ".png"):
        messagebox.showerror("Error", "Only png images are valid.")
        return
    elif (len(newName) == 0):
        messagebox.showerror("Error", "Name for the new image is not provided.")
    else:    
        try:
            encryptImg.setMessage(path, message, newName)
        except BaseException as error:
            messagebox.showerror("Error", "Failed to hide.")
            
def getCommand():
    global top
    path = top.etGetPath.get().strip()
    if (len(path) <= 4):
        messagebox.showerror("Error", "No legal path provided.")
        return
    else:
        try:
            message = encryptImg.getMessage(path)
        except BaseException as error:
            messagebox.showerror("Error", "Failed to read.") 
            return
        
        messagebox.showinfo("Message",message)
        
    

class ImageHide:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("419x526+781+75")
        top.title("ImageHide")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.04, rely=0.03, relheight=0.52, relwidth=0.92)
        self.Frame1.configure(relief=RAISED)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=RAISED)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=386)

        self.lblSet = Label(self.Frame1)
        self.lblSet.place(relx=0.03, rely=0.04, height=31, width=118)
        self.lblSet.configure(activebackground="#f9f9f9")
        self.lblSet.configure(activeforeground="black")
        self.lblSet.configure(anchor=W)
        self.lblSet.configure(background="#d9d9d9")
        self.lblSet.configure(disabledforeground="#a3a3a3")
        self.lblSet.configure(foreground="#000000")
        self.lblSet.configure(highlightbackground="#d9d9d9")
        self.lblSet.configure(highlightcolor="black")
        self.lblSet.configure(text='''Hide Message''')

        self.etSetPath = Entry(self.Frame1)
        self.etSetPath.place(relx=0.34, rely=0.22,height=25, relwidth=0.63)
        self.etSetPath.configure(background="white")
        self.etSetPath.configure(disabledforeground="#a3a3a3")
        self.etSetPath.configure(font="TkFixedFont")
        self.etSetPath.configure(foreground="#000000")
        self.etSetPath.configure(highlightbackground="#d9d9d9")
        self.etSetPath.configure(highlightcolor="black")
        self.etSetPath.configure(insertbackground="black")
        self.etSetPath.configure(selectbackground="#c4c4c4")
        self.etSetPath.configure(selectforeground="black")
        self.etSetPath.configure(width=245)

        self.lblPathSet = Label(self.Frame1)
        self.lblPathSet.place(relx=0.03, rely=0.2, height=31, width=110)
        self.lblPathSet.configure(activebackground="#f9f9f9")
        self.lblPathSet.configure(activeforeground="black")
        self.lblPathSet.configure(anchor=W)
        self.lblPathSet.configure(background="#d9d9d9")
        self.lblPathSet.configure(disabledforeground="#a3a3a3")
        self.lblPathSet.configure(font=font9)
        self.lblPathSet.configure(foreground="#000000")
        self.lblPathSet.configure(highlightbackground="#d9d9d9")
        self.lblPathSet.configure(highlightcolor="black")
        self.lblPathSet.configure(text='''Image path:''')
        self.lblPathSet.configure(width=110)

        self.etSetMessage = Entry(self.Frame1)
        self.etSetMessage.place(relx=0.34, rely=0.36,height=25, relwidth=0.63)
        self.etSetMessage.configure(background="white")
        self.etSetMessage.configure(disabledforeground="#a3a3a3")
        self.etSetMessage.configure(font="TkFixedFont")
        self.etSetMessage.configure(foreground="#000000")
        self.etSetMessage.configure(highlightbackground="#d9d9d9")
        self.etSetMessage.configure(highlightcolor="black")
        self.etSetMessage.configure(insertbackground="black")
        self.etSetMessage.configure(selectbackground="#c4c4c4")
        self.etSetMessage.configure(selectforeground="black")
        self.etSetMessage.configure(width=245)

        self.lblNewName = Label(self.Frame1)
        self.lblNewName.place(relx=0.03, rely=0.49, height=31, width=153)
        self.lblNewName.configure(activebackground="#f9f9f9")
        self.lblNewName.configure(activeforeground="black")
        self.lblNewName.configure(anchor=W)
        self.lblNewName.configure(background="#d9d9d9")
        self.lblNewName.configure(disabledforeground="#a3a3a3")
        self.lblNewName.configure(foreground="#000000")
        self.lblNewName.configure(highlightbackground="#d9d9d9")
        self.lblNewName.configure(highlightcolor="black")
        self.lblNewName.configure(text='''New image name:''')

        self.etNewName = Entry(self.Frame1)
        self.etNewName.place(relx=0.47, rely=0.51,height=26, relwidth=0.5)
        self.etNewName.configure(background="white")
        self.etNewName.configure(disabledforeground="#a3a3a3")
        self.etNewName.configure(font="TkFixedFont")
        self.etNewName.configure(foreground="#000000")
        self.etNewName.configure(highlightbackground="#d9d9d9")
        self.etNewName.configure(highlightcolor="black")
        self.etNewName.configure(insertbackground="black")
        self.etNewName.configure(selectbackground="#c4c4c4")
        self.etNewName.configure(selectforeground="black")
        self.etNewName.configure(width=194)

        self.btSet = Button(self.Frame1, command = setCommand)
        self.btSet.place(relx=0.31, rely=0.76, height=42, width=120)
        self.btSet.configure(activebackground="#d9d9d9")
        self.btSet.configure(activeforeground="#000000")
        self.btSet.configure(background="#d9d9d9")
        self.btSet.configure(disabledforeground="#a3a3a3")
        self.btSet.configure(foreground="#000000")
        self.btSet.configure(highlightbackground="#d9d9d9")
        self.btSet.configure(highlightcolor="black")
        self.btSet.configure(pady="0")
        self.btSet.configure(text='''Hide!''')
        self.btSet.configure(width=120)

        self.lblPathSet_1 = Label(self.Frame1)
        self.lblPathSet_1.place(relx=0.03, rely=0.34, height=31, width=110)
        self.lblPathSet_1.configure(activebackground="#f9f9f9")
        self.lblPathSet_1.configure(activeforeground="black")
        self.lblPathSet_1.configure(anchor=W)
        self.lblPathSet_1.configure(background="#d9d9d9")
        self.lblPathSet_1.configure(disabledforeground="#a3a3a3")
        self.lblPathSet_1.configure(font=font9)
        self.lblPathSet_1.configure(foreground="#000000")
        self.lblPathSet_1.configure(highlightbackground="#d9d9d9")
        self.lblPathSet_1.configure(highlightcolor="black")
        self.lblPathSet_1.configure(text='''Message:''')

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.04, rely=0.59, relheight=0.33, relwidth=0.92)
        self.Frame2.configure(relief=RAISED)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=RAISED)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=386)

        self.lblGet = Label(self.Frame2)
        self.lblGet.place(relx=0.03, rely=0.06, height=31, width=121)
        self.lblGet.configure(activebackground="#f9f9f9")
        self.lblGet.configure(activeforeground="black")
        self.lblGet.configure(anchor=W)
        self.lblGet.configure(background="#d9d9d9")
        self.lblGet.configure(disabledforeground="#a3a3a3")
        self.lblGet.configure(foreground="#000000")
        self.lblGet.configure(highlightbackground="#d9d9d9")
        self.lblGet.configure(highlightcolor="black")
        self.lblGet.configure(text='''Read Message''')

        self.etGetPath = Entry(self.Frame2)
        self.etGetPath.place(relx=0.34, rely=0.34,height=25, relwidth=0.63)
        self.etGetPath.configure(background="white")
        self.etGetPath.configure(disabledforeground="#a3a3a3")
        self.etGetPath.configure(font="TkFixedFont")
        self.etGetPath.configure(foreground="#000000")
        self.etGetPath.configure(highlightbackground="#d9d9d9")
        self.etGetPath.configure(highlightcolor="black")
        self.etGetPath.configure(insertbackground="black")
        self.etGetPath.configure(selectbackground="#c4c4c4")
        self.etGetPath.configure(selectforeground="black")
        self.etGetPath.configure(width=245)

        self.lblPathSet_1 = Label(self.Frame2)
        self.lblPathSet_1.place(relx=0.03, rely=0.31, height=31, width=106)
        self.lblPathSet_1.configure(activebackground="#f9f9f9")
        self.lblPathSet_1.configure(activeforeground="black")
        self.lblPathSet_1.configure(anchor=W)
        self.lblPathSet_1.configure(background="#d9d9d9")
        self.lblPathSet_1.configure(disabledforeground="#a3a3a3")
        self.lblPathSet_1.configure(foreground="#000000")
        self.lblPathSet_1.configure(highlightbackground="#d9d9d9")
        self.lblPathSet_1.configure(highlightcolor="black")
        self.lblPathSet_1.configure(text='''Image path:''')

        self.btGet = Button(self.Frame2, command = getCommand)
        self.btGet.place(relx=0.31, rely=0.63, height=42, width=120)
        self.btGet.configure(activebackground="#d9d9d9")
        self.btGet.configure(activeforeground="#000000")
        self.btGet.configure(background="#d9d9d9")
        self.btGet.configure(disabledforeground="#a3a3a3")
        self.btGet.configure(foreground="#000000")
        self.btGet.configure(highlightbackground="#d9d9d9")
        self.btGet.configure(highlightcolor="black")
        self.btGet.configure(pady="0")
        self.btGet.configure(text='''Read!''')
        self.btGet.configure(width=120)

        self.lblCredit = Label(top)
        self.lblCredit.place(relx=0.04, rely=0.93, height=31, width=172)
        self.lblCredit.configure(activebackground="#f9f9f9")
        self.lblCredit.configure(activeforeground="black")
        self.lblCredit.configure(anchor=W)
        self.lblCredit.configure(background="#d9d9d9")
        self.lblCredit.configure(disabledforeground="#a3a3a3")
        self.lblCredit.configure(foreground="#000000")
        self.lblCredit.configure(highlightbackground="#d9d9d9")
        self.lblCredit.configure(highlightcolor="black")
        self.lblCredit.configure(text='''Created by Ben Izhak''')






if __name__ == '__main__':
    vp_start_gui()

